# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4adbf8b81a4bd73fec530709c669e1f6b67f4b76024109fee7fd0453da0f79aa2840289a629d6f1cf5c7536774097eeb9edbccad47a0844fe5282f52be564cc

test:
  secret_key_base: 3d82b04da941bd73dd4fcd15521d91b259abccb5a333d4402ca1ee233364651c0816ef85bba7996977eb17273546c9248f8c11e5be7ebc7e2d3827435f5d643b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
